import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

interface ProviderSeed {
  slug: string;
  name: string;
  category: string;
  logoUrl: string | null;
  websiteUrl: string | null;
  integrationState: string;
  description: string | null;
  displayOrder: number;
  isActive: boolean;
}

const providers: ProviderSeed[] = [
  // ─── FULL-SERVICE ──────────────────────────────────────────────────
  {
    slug: "square",
    name: "Square Appointments",
    category: "full-service",
    logoUrl: "https://logo.clearbit.com/squareup.com",
    websiteUrl: "https://squareup.com",
    integrationState: "live",
    description: "All-in-one POS and appointment scheduling by Square.",
    displayOrder: 1,
    isActive: true,
  },
  {
    slug: "booksy",
    name: "Booksy",
    category: "full-service",
    logoUrl: "https://logo.clearbit.com/booksy.com",
    websiteUrl: "https://booksy.com",
    integrationState: "waitlist",
    description: "Booking and business management for beauty professionals.",
    displayOrder: 2,
    isActive: true,
  },
  {
    slug: "fresha",
    name: "Fresha",
    category: "full-service",
    logoUrl: "https://logo.clearbit.com/fresha.com",
    websiteUrl: "https://fresha.com",
    integrationState: "waitlist",
    description: "Free salon and spa booking software used worldwide.",
    displayOrder: 3,
    isActive: true,
  },
  {
    slug: "glossgenius",
    name: "GlossGenius",
    category: "full-service",
    logoUrl: "https://logo.clearbit.com/glossgenius.com",
    websiteUrl: "https://glossgenius.com",
    integrationState: "waitlist",
    description: "All-in-one app for independent beauty professionals.",
    displayOrder: 4,
    isActive: true,
  },
  {
    slug: "vagaro",
    name: "Vagaro",
    category: "full-service",
    logoUrl: "https://logo.clearbit.com/vagaro.com",
    websiteUrl: "https://vagaro.com",
    integrationState: "waitlist",
    description: "Salon, spa, and fitness booking and business management.",
    displayOrder: 5,
    isActive: true,
  },
  {
    slug: "mindbody",
    name: "Mindbody",
    category: "full-service",
    logoUrl: "https://logo.clearbit.com/mindbodyonline.com",
    websiteUrl: "https://mindbodyonline.com",
    integrationState: "waitlist",
    description: "Wellness industry software for scheduling and payments.",
    displayOrder: 6,
    isActive: true,
  },
  {
    slug: "meevo",
    name: "Meevo",
    category: "full-service",
    logoUrl: "https://logo.clearbit.com/meevo.com",
    websiteUrl: "https://meevo.com",
    integrationState: "waitlist",
    description: "Cloud-based salon and spa management software.",
    displayOrder: 7,
    isActive: true,
  },
  {
    slug: "phorest",
    name: "Phorest",
    category: "full-service",
    logoUrl: "https://logo.clearbit.com/phorest.com",
    websiteUrl: "https://phorest.com",
    integrationState: "waitlist",
    description: "Salon software focused on client retention and marketing.",
    displayOrder: 8,
    isActive: true,
  },
  {
    slug: "boulevard",
    name: "Boulevard",
    category: "full-service",
    logoUrl: "https://logo.clearbit.com/joinblvd.com",
    websiteUrl: "https://joinblvd.com",
    integrationState: "waitlist",
    description: "Client experience platform for salons and spas.",
    displayOrder: 9,
    isActive: true,
  },
  {
    slug: "zenoti",
    name: "Zenoti",
    category: "full-service",
    logoUrl: "https://logo.clearbit.com/zenoti.com",
    websiteUrl: "https://zenoti.com",
    integrationState: "waitlist",
    description: "Enterprise cloud software for spas, salons, and med spas.",
    displayOrder: 10,
    isActive: true,
  },
  {
    slug: "rosy",
    name: "Rosy",
    category: "full-service",
    logoUrl: "https://logo.clearbit.com/rosysalonsoftware.com",
    websiteUrl: "https://rosysalonsoftware.com",
    integrationState: "waitlist",
    description: "Cloud-based salon and spa management solution.",
    displayOrder: 11,
    isActive: true,
  },
  {
    slug: "envision-salon",
    name: "Envision Salon",
    category: "full-service",
    logoUrl: "https://logo.clearbit.com/envisionsalon.com",
    websiteUrl: "https://envisionsalon.com",
    integrationState: "waitlist",
    description: "Full-featured salon management and POS system.",
    displayOrder: 12,
    isActive: true,
  },
  {
    slug: "mytime",
    name: "MyTime",
    category: "full-service",
    logoUrl: "https://logo.clearbit.com/mytime.com",
    websiteUrl: "https://mytime.com",
    integrationState: "waitlist",
    description: "End-to-end business management for local services.",
    displayOrder: 13,
    isActive: true,
  },
  {
    slug: "saloniris",
    name: "SalonIris",
    category: "full-service",
    logoUrl: "https://logo.clearbit.com/saloniris.com",
    websiteUrl: "https://saloniris.com",
    integrationState: "waitlist",
    description: "Scheduling and management software for salons.",
    displayOrder: 14,
    isActive: true,
  },
  {
    slug: "daysmart-salon",
    name: "DaySmart Salon",
    category: "full-service",
    logoUrl: "https://logo.clearbit.com/daysmart.com",
    websiteUrl: "https://daysmart.com",
    integrationState: "waitlist",
    description: "Appointment book, POS, and marketing for salons.",
    displayOrder: 15,
    isActive: true,
  },
  {
    slug: "shortcuts",
    name: "Shortcuts",
    category: "full-service",
    logoUrl: "https://logo.clearbit.com/shortcuts.com.au",
    websiteUrl: "https://shortcuts.com.au",
    integrationState: "waitlist",
    description: "Salon and spa software used in over 40 countries.",
    displayOrder: 16,
    isActive: true,
  },
  {
    slug: "salonized",
    name: "Salonized",
    category: "full-service",
    logoUrl: "https://logo.clearbit.com/salonized.com",
    websiteUrl: "https://salonized.com",
    integrationState: "waitlist",
    description: "Simple salon software for scheduling and checkout.",
    displayOrder: 17,
    isActive: true,
  },
  {
    slug: "treatwell",
    name: "Treatwell",
    category: "full-service",
    logoUrl: "https://logo.clearbit.com/treatwell.com",
    websiteUrl: "https://treatwell.com",
    integrationState: "waitlist",
    description: "Europe's largest salon booking platform.",
    displayOrder: 18,
    isActive: true,
  },
  {
    slug: "timely",
    name: "Timely",
    category: "full-service",
    logoUrl: "https://logo.clearbit.com/gettimely.com",
    websiteUrl: "https://gettimely.com",
    integrationState: "waitlist",
    description: "Online booking and salon management from New Zealand.",
    displayOrder: 19,
    isActive: true,
  },
  {
    slug: "acuity-scheduling",
    name: "Acuity Scheduling",
    category: "full-service",
    logoUrl: "https://logo.clearbit.com/acuityscheduling.com",
    websiteUrl: "https://acuityscheduling.com",
    integrationState: "waitlist",
    description: "Online appointment scheduling by Squarespace.",
    displayOrder: 20,
    isActive: true,
  },
  {
    slug: "schedulicity",
    name: "Schedulicity",
    category: "full-service",
    logoUrl: "https://logo.clearbit.com/schedulicity.com",
    websiteUrl: "https://schedulicity.com",
    integrationState: "waitlist",
    description: "Online scheduling and marketing for service businesses.",
    displayOrder: 21,
    isActive: true,
  },
  {
    slug: "booker",
    name: "Booker by Mindbody",
    category: "full-service",
    logoUrl: "https://logo.clearbit.com/booker.com",
    websiteUrl: "https://booker.com",
    integrationState: "waitlist",
    description: "Spa and salon business management by Mindbody.",
    displayOrder: 22,
    isActive: true,
  },
  {
    slug: "salonist",
    name: "Salonist",
    category: "full-service",
    logoUrl: "https://logo.clearbit.com/salonist.io",
    websiteUrl: "https://salonist.io",
    integrationState: "waitlist",
    description: "Cloud-based salon and spa management platform.",
    displayOrder: 23,
    isActive: true,
  },

  // ─── BARBERSHOP ────────────────────────────────────────────────────
  {
    slug: "squire",
    name: "Squire",
    category: "barbershop",
    logoUrl: "https://logo.clearbit.com/getsquire.com",
    websiteUrl: "https://getsquire.com",
    integrationState: "waitlist",
    description: "Barbershop management and booking platform.",
    displayOrder: 100,
    isActive: true,
  },
  {
    slug: "thecut",
    name: "theCut",
    category: "barbershop",
    logoUrl: "https://logo.clearbit.com/thecut.co",
    websiteUrl: "https://thecut.co",
    integrationState: "waitlist",
    description: "Barber booking app connecting clients and barbers.",
    displayOrder: 101,
    isActive: true,
  },
  {
    slug: "barberbooker",
    name: "BarberBooker",
    category: "barbershop",
    logoUrl: "https://logo.clearbit.com/barberbooker.com",
    websiteUrl: "https://barberbooker.com",
    integrationState: "waitlist",
    description: "Online booking system built for barbershops.",
    displayOrder: 102,
    isActive: true,
  },
  {
    slug: "cuts-booking",
    name: "Cuts Booking",
    category: "barbershop",
    logoUrl: "https://logo.clearbit.com/cutsbooking.com",
    websiteUrl: "https://cutsbooking.com",
    integrationState: "waitlist",
    description: "Barbershop scheduling and management app.",
    displayOrder: 103,
    isActive: true,
  },

  // ─── INDEPENDENT / BOOTH ──────────────────────────────────────────
  {
    slug: "styleseat",
    name: "StyleSeat",
    category: "independent",
    logoUrl: "https://logo.clearbit.com/styleseat.com",
    websiteUrl: "https://styleseat.com",
    integrationState: "waitlist",
    description: "Marketplace and booking for independent beauty pros.",
    displayOrder: 100,
    isActive: true,
  },
  {
    slug: "goldie",
    name: "Goldie",
    category: "independent",
    logoUrl: "https://logo.clearbit.com/goldie.io",
    websiteUrl: "https://goldie.io",
    integrationState: "waitlist",
    description: "Appointment scheduling app for solo beauty professionals.",
    displayOrder: 101,
    isActive: true,
  },
  {
    slug: "beu",
    name: "Beu",
    category: "independent",
    logoUrl: "https://logo.clearbit.com/beu.io",
    websiteUrl: "https://beu.io",
    integrationState: "waitlist",
    description: "Booking and payments for independent stylists.",
    displayOrder: 102,
    isActive: true,
  },
  {
    slug: "setmo",
    name: "Setmo",
    category: "independent",
    logoUrl: "https://logo.clearbit.com/setmo.com",
    websiteUrl: "https://setmo.com",
    integrationState: "waitlist",
    description: "Simple booking for booth renters and freelancers.",
    displayOrder: 103,
    isActive: true,
  },
  {
    slug: "honeybook",
    name: "HoneyBook",
    category: "independent",
    logoUrl: "https://logo.clearbit.com/honeybook.com",
    websiteUrl: "https://honeybook.com",
    integrationState: "waitlist",
    description: "Client management platform for independent businesses.",
    displayOrder: 104,
    isActive: true,
  },

  // ─── MED SPA ───────────────────────────────────────────────────────
  {
    slug: "aesthetic-record",
    name: "AestheticRecord",
    category: "med-spa",
    logoUrl: "https://logo.clearbit.com/aestheticrecord.com",
    websiteUrl: "https://aestheticrecord.com",
    integrationState: "waitlist",
    description: "Practice management software for medical aesthetics.",
    displayOrder: 100,
    isActive: true,
  },
  {
    slug: "mangomint",
    name: "Mangomint",
    category: "med-spa",
    logoUrl: "https://logo.clearbit.com/mangomint.com",
    websiteUrl: "https://mangomint.com",
    integrationState: "waitlist",
    description: "Smart salon and spa management software.",
    displayOrder: 101,
    isActive: true,
  },
  {
    slug: "patientnow",
    name: "PatientNow",
    category: "med-spa",
    logoUrl: "https://logo.clearbit.com/patientnow.com",
    websiteUrl: "https://patientnow.com",
    integrationState: "waitlist",
    description: "EMR and practice management for aesthetic medicine.",
    displayOrder: 102,
    isActive: true,
  },
  {
    slug: "nextech",
    name: "Nextech",
    category: "med-spa",
    logoUrl: "https://logo.clearbit.com/nextech.com",
    websiteUrl: "https://nextech.com",
    integrationState: "waitlist",
    description: "EHR and practice management for specialty physicians.",
    displayOrder: 103,
    isActive: true,
  },
  {
    slug: "envision-spa",
    name: "Envision Spa",
    category: "med-spa",
    logoUrl: "https://logo.clearbit.com/envisionsalon.com",
    websiteUrl: "https://envisionsalon.com",
    integrationState: "waitlist",
    description: "Full-featured spa management and POS system.",
    displayOrder: 104,
    isActive: true,
  },
  {
    slug: "aesthetic-pro",
    name: "Aesthetic Pro",
    category: "med-spa",
    logoUrl: "https://logo.clearbit.com/aestheticpro.com",
    websiteUrl: "https://aestheticpro.com",
    integrationState: "waitlist",
    description: "Cloud-based med spa management and patient records.",
    displayOrder: 105,
    isActive: true,
  },

  // ─── NAIL ──────────────────────────────────────────────────────────
  {
    slug: "nailbook",
    name: "NailBook",
    category: "nail",
    logoUrl: "https://logo.clearbit.com/nailbook.jp",
    websiteUrl: "https://nailbook.jp",
    integrationState: "waitlist",
    description: "Nail salon booking and gallery platform.",
    displayOrder: 100,
    isActive: true,
  },
  {
    slug: "salontarget-nail",
    name: "SalonTarget Nail",
    category: "nail",
    logoUrl: "https://logo.clearbit.com/salontarget.com",
    websiteUrl: "https://salontarget.com",
    integrationState: "waitlist",
    description: "POS and management software for nail salons.",
    displayOrder: 101,
    isActive: true,
  },

  // ─── ENTERPRISE ────────────────────────────────────────────────────
  {
    slug: "millennium",
    name: "Millennium by Meevo",
    category: "enterprise",
    logoUrl: "https://logo.clearbit.com/hfranchinc.com",
    websiteUrl: "https://hfranchinc.com",
    integrationState: "waitlist",
    description: "Enterprise salon and spa management software.",
    displayOrder: 100,
    isActive: true,
  },
  {
    slug: "insight-salon",
    name: "Insight Salon",
    category: "enterprise",
    logoUrl: "https://logo.clearbit.com/insightsalonandspa.com",
    websiteUrl: "https://insightsalonandspa.com",
    integrationState: "waitlist",
    description: "Business intelligence and management for salons.",
    displayOrder: 101,
    isActive: true,
  },
  {
    slug: "harms-software",
    name: "Harms Software",
    category: "enterprise",
    logoUrl: "https://logo.clearbit.com/harmssoftware.com",
    websiteUrl: "https://harmssoftware.com",
    integrationState: "waitlist",
    description: "Salon management software for multi-location businesses.",
    displayOrder: 102,
    isActive: true,
  },

  // ─── ESTHETICIAN ───────────────────────────────────────────────────
  {
    slug: "jane-app",
    name: "Jane App",
    category: "esthetician",
    logoUrl: "https://logo.clearbit.com/jane.app",
    websiteUrl: "https://jane.app",
    integrationState: "waitlist",
    description: "Practice management for health and wellness practitioners.",
    displayOrder: 100,
    isActive: true,
  },
  {
    slug: "simplepractice",
    name: "SimplePractice",
    category: "esthetician",
    logoUrl: "https://logo.clearbit.com/simplepractice.com",
    websiteUrl: "https://simplepractice.com",
    integrationState: "waitlist",
    description: "All-in-one practice management for wellness pros.",
    displayOrder: 101,
    isActive: true,
  },
  {
    slug: "noterro",
    name: "Noterro",
    category: "esthetician",
    logoUrl: "https://logo.clearbit.com/noterro.com",
    websiteUrl: "https://noterro.com",
    integrationState: "waitlist",
    description: "Charting and practice management for bodyworkers.",
    displayOrder: 102,
    isActive: true,
  },

  // ─── BOOKKEEPING ───────────────────────────────────────────────────
  {
    slug: "quickbooks-self-employed",
    name: "QuickBooks Self-Employed",
    category: "bookkeeping",
    logoUrl: "https://logo.clearbit.com/quickbooks.intuit.com",
    websiteUrl: "https://quickbooks.intuit.com",
    integrationState: "waitlist",
    description: "Tax and expense tracking for freelancers.",
    displayOrder: 100,
    isActive: true,
  },
  {
    slug: "quickbooks-online",
    name: "QuickBooks Online",
    category: "bookkeeping",
    logoUrl: "https://logo.clearbit.com/quickbooks.intuit.com",
    websiteUrl: "https://quickbooks.intuit.com",
    integrationState: "waitlist",
    description: "Cloud accounting and bookkeeping for small businesses.",
    displayOrder: 101,
    isActive: true,
  },
  {
    slug: "xero",
    name: "Xero",
    category: "bookkeeping",
    logoUrl: "https://logo.clearbit.com/xero.com",
    websiteUrl: "https://xero.com",
    integrationState: "waitlist",
    description: "Cloud-based accounting software for small businesses.",
    displayOrder: 102,
    isActive: true,
  },
  {
    slug: "wave",
    name: "Wave",
    category: "bookkeeping",
    logoUrl: "https://logo.clearbit.com/waveapps.com",
    websiteUrl: "https://waveapps.com",
    integrationState: "waitlist",
    description: "Free invoicing, accounting, and receipt scanning.",
    displayOrder: 103,
    isActive: true,
  },

  // ─── OTHER ─────────────────────────────────────────────────────────
  {
    slug: "kasse",
    name: "Kasse by RunMySalon",
    category: "other",
    logoUrl: null,
    websiteUrl: null,
    integrationState: "in_development",
    description: "RunMySalon's built-in point-of-sale system.",
    displayOrder: 0,
    isActive: true,
  },
  {
    slug: "spreadsheets",
    name: "I use spreadsheets or paper",
    category: "other",
    logoUrl: null,
    websiteUrl: null,
    integrationState: "waitlist",
    description: null,
    displayOrder: 998,
    isActive: true,
  },
  {
    slug: "starting-fresh",
    name: "I'm starting fresh",
    category: "other",
    logoUrl: null,
    websiteUrl: null,
    integrationState: "waitlist",
    description: null,
    displayOrder: 999,
    isActive: true,
  },
  {
    slug: "other",
    name: "Other — not listed",
    category: "other",
    logoUrl: null,
    websiteUrl: null,
    integrationState: "waitlist",
    description: null,
    displayOrder: 1000,
    isActive: true,
  },
];

async function main() {
  console.log(`Seeding ${providers.length} software providers...`);

  let created = 0;
  let updated = 0;

  for (const provider of providers) {
    const result = await prisma.softwareProvider.upsert({
      where: { slug: provider.slug },
      update: {
        name: provider.name,
        category: provider.category,
        logoUrl: provider.logoUrl,
        websiteUrl: provider.websiteUrl,
        integrationState: provider.integrationState,
        description: provider.description,
        displayOrder: provider.displayOrder,
        isActive: provider.isActive,
      },
      create: provider,
    });

    // If updatedAt is very close to createdAt, it was freshly created
    const isNew =
      Math.abs(result.createdAt.getTime() - result.updatedAt.getTime()) < 1000;
    if (isNew) created++;
    else updated++;
  }

  console.log(
    `Done. ${created} created, ${updated} updated. Total: ${providers.length} providers.`
  );
}

main()
  .catch((e) => {
    console.error("Seed failed:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
