import { PrismaClient } from "@prisma/client"
const prisma = new PrismaClient()

const PLACEHOLDER_TOS = `
\u26a0\ufe0f THIS IS A PLACEHOLDER DOCUMENT. REAL LEGAL TERMS MUST BE DRAFTED BY AN ATTORNEY BEFORE PRODUCTION USE. DO NOT LAUNCH WITHOUT REPLACING THIS DOCUMENT.

RUNMYSALON TERMS OF SERVICE
Version: v0-placeholder
Last Updated: ${new Date().toISOString().split("T")[0]}

1. DEFINITIONS

For the purposes of this Agreement, the following terms shall have the meanings set forth below. "RunMySalon" refers to the salon management platform operated by Reyna Tech LLC, a Delaware limited liability company, including all associated web applications, mobile applications, APIs, integrations, and related services. "Platform" means the RunMySalon software-as-a-service application and all features, tools, dashboards, and functionality accessible through the Platform. "Subscriber" means any individual or business entity that creates an account on the Platform, whether operating under a free trial or a paid subscription plan. "Authorized User" means any employee, contractor, or agent of a Subscriber who has been granted access credentials to use the Platform on behalf of the Subscriber. "Salon Data" means all information entered into, generated by, or stored within the Platform by a Subscriber or its Authorized Users, including but not limited to client records, appointment schedules, financial transactions, inventory data, employee records, and analytics. "Third-Party Services" means any external applications, payment processors, scheduling tools, or integrations that connect to or interact with the Platform. "Service Period" means the duration of the Subscriber's active subscription, whether monthly or annual. "Effective Date" means the date on which the Subscriber first accepts these Terms of Service by creating an account or electronically signing this Agreement.

[PLACEHOLDER - ATTORNEY REVIEW REQUIRED]

2. LICENSE GRANT

Subject to the terms and conditions of this Agreement, Reyna Tech LLC hereby grants the Subscriber a limited, non-exclusive, non-transferable, revocable license to access and use the Platform during the Service Period solely for the Subscriber's internal business operations related to salon management. This license permits the Subscriber to create Authorized User accounts in accordance with the limits of their selected subscription tier. The Subscriber shall not sublicense, resell, distribute, or otherwise make the Platform available to any third party without prior written consent from Reyna Tech LLC. The Platform and all intellectual property rights therein, including but not limited to source code, object code, algorithms, user interface designs, documentation, trademarks, and trade secrets, remain the sole and exclusive property of Reyna Tech LLC. No rights are granted to the Subscriber other than those expressly stated in this Agreement. Any unauthorized use of the Platform, including reverse engineering, decompilation, or creation of derivative works, shall constitute a material breach of this Agreement and may result in immediate termination of the Subscriber's account and pursuit of all available legal remedies.

[PLACEHOLDER - ATTORNEY REVIEW REQUIRED]

3. PAYMENT TERMS

Subscribers on paid plans agree to pay all fees associated with their selected subscription tier as published on the RunMySalon pricing page at the time of enrollment. All fees are quoted in United States Dollars and are exclusive of applicable sales tax, value-added tax, or other governmental levies, which shall be the sole responsibility of the Subscriber. Subscription fees are billed in advance on a recurring basis, either monthly or annually, depending on the billing cycle selected by the Subscriber. Payment shall be made via credit card, debit card, or ACH bank transfer through the Platform's designated payment processor. Failure to make timely payment may result in suspension or termination of access to the Platform. Reyna Tech LLC reserves the right to modify pricing with thirty (30) days' prior written notice to the Subscriber. Continued use of the Platform after a price change takes effect constitutes acceptance of the new pricing. Refunds are generally not provided for partial billing periods, except where required by applicable law. Disputes regarding charges must be raised within sixty (60) days of the billing date.

[PLACEHOLDER - ATTORNEY REVIEW REQUIRED]

4. FREE TRIAL

Reyna Tech LLC may, at its sole discretion, offer prospective Subscribers a free trial period to evaluate the Platform prior to committing to a paid subscription. The duration and features available during the free trial shall be as specified at the time of enrollment. During the free trial, the Subscriber shall have access to the Platform's features as determined by Reyna Tech LLC, which may be a subset of the full feature set available to paying Subscribers. At the conclusion of the free trial period, the Subscriber's account will either convert to a paid subscription (if payment information has been provided and auto-conversion is enabled) or will be suspended until a paid plan is selected. Reyna Tech LLC reserves the right to modify, limit, or discontinue free trial offers at any time without prior notice. Free trial accounts are limited to one per Subscriber entity, and any attempt to create multiple trial accounts to circumvent this limitation may result in termination of all associated accounts. Data entered during the free trial period will be retained and available upon conversion to a paid plan, subject to the Platform's data retention policies.

[PLACEHOLDER - ATTORNEY REVIEW REQUIRED]

5. DATA OWNERSHIP

The Subscriber retains full ownership of all Salon Data entered into the Platform by the Subscriber or its Authorized Users. Reyna Tech LLC does not claim any ownership interest in Salon Data. The Subscriber grants Reyna Tech LLC a limited, non-exclusive license to host, store, process, and display Salon Data solely for the purpose of providing and improving the Platform's services. Reyna Tech LLC may use aggregated, anonymized, and de-identified data derived from Salon Data for purposes including but not limited to analytics, benchmarking, product improvement, and industry research, provided that such aggregated data cannot reasonably be used to identify the Subscriber or any individual client of the Subscriber. Upon termination of the Subscriber's account, Reyna Tech LLC shall make Salon Data available for export for a period of thirty (30) days following termination. After this export period, Reyna Tech LLC may delete Salon Data from its active systems, though residual copies may persist in backup systems for a reasonable period. The Subscriber is solely responsible for maintaining independent backups of its Salon Data as it deems appropriate.

[PLACEHOLDER - ATTORNEY REVIEW REQUIRED]

6. THIRD-PARTY INTEGRATIONS

The Platform may offer integrations with Third-Party Services, including but not limited to Square, Stripe, Google Calendar, Twilio, and various social media platforms. These integrations are provided as a convenience and are subject to the terms, conditions, and privacy policies of the respective Third-Party Service providers. Reyna Tech LLC does not warrant, endorse, or assume responsibility for the accuracy, reliability, or performance of any Third-Party Service. The Subscriber acknowledges that enabling a Third-Party Service integration may require granting that Third-Party Service access to certain Salon Data, and the Subscriber assumes all risk associated with such data sharing. Reyna Tech LLC shall not be liable for any loss, damage, or breach arising from the Subscriber's use of or reliance on any Third-Party Service. In the event that a Third-Party Service modifies its API, discontinues service, or changes its terms in a manner that affects integration with the Platform, Reyna Tech LLC shall use commercially reasonable efforts to maintain compatibility but does not guarantee uninterrupted integration functionality. The Subscriber is responsible for reviewing and complying with the terms of service of any Third-Party Service it connects to the Platform.

[PLACEHOLDER - ATTORNEY REVIEW REQUIRED]

7. INDEMNIFICATION

The Subscriber agrees to indemnify, defend, and hold harmless Reyna Tech LLC, its officers, directors, employees, agents, affiliates, successors, and assigns from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees and court costs) arising out of or relating to: (a) the Subscriber's use of or inability to use the Platform; (b) the Subscriber's violation of any provision of this Agreement; (c) the Subscriber's violation of any applicable law, regulation, or third-party right, including but not limited to employment laws, consumer protection statutes, and data privacy regulations; (d) any content or data submitted to the Platform by the Subscriber or its Authorized Users; or (e) any dispute between the Subscriber and its clients, employees, or contractors. This indemnification obligation shall survive the termination of this Agreement. Reyna Tech LLC reserves the right, at its own expense, to assume exclusive defense and control of any matter subject to indemnification by the Subscriber, in which case the Subscriber shall cooperate with Reyna Tech LLC in asserting any available defenses.

[PLACEHOLDER - ATTORNEY REVIEW REQUIRED]

8. LIMITATION OF LIABILITY

TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL REYNA TECH LLC, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, LOSS OF DATA, LOSS OF BUSINESS OPPORTUNITY, OR LOSS OF GOODWILL, ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT OR THE USE OF THE PLATFORM, REGARDLESS OF WHETHER SUCH DAMAGES ARE BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR ANY OTHER LEGAL THEORY, AND REGARDLESS OF WHETHER REYNA TECH LLC HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE TOTAL AGGREGATE LIABILITY OF REYNA TECH LLC FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THIS AGREEMENT SHALL NOT EXCEED THE TOTAL AMOUNT OF FEES PAID BY THE SUBSCRIBER TO REYNA TECH LLC DURING THE TWELVE (12) MONTH PERIOD IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM. THE SUBSCRIBER ACKNOWLEDGES THAT THE FEES CHARGED BY REYNA TECH LLC REFLECT THE ALLOCATION OF RISK SET FORTH IN THIS AGREEMENT AND THAT REYNA TECH LLC WOULD NOT ENTER INTO THIS AGREEMENT WITHOUT THESE LIMITATIONS ON LIABILITY.

[PLACEHOLDER - ATTORNEY REVIEW REQUIRED]

9. TERMINATION

Either party may terminate this Agreement at any time for any reason by providing written notice to the other party. The Subscriber may terminate by canceling their subscription through the Platform's account settings or by contacting customer support. Reyna Tech LLC may terminate or suspend the Subscriber's account immediately, without prior notice, if: (a) the Subscriber breaches any provision of this Agreement; (b) the Subscriber fails to make timely payment of subscription fees; (c) the Subscriber engages in any activity that is harmful to the Platform, other Subscribers, or Reyna Tech LLC's reputation; or (d) Reyna Tech LLC is required to do so by law or regulation. Upon termination, the Subscriber's right to access and use the Platform shall immediately cease. Sections of this Agreement that by their nature should survive termination, including but not limited to indemnification, limitation of liability, data ownership, and dispute resolution, shall remain in full force and effect following termination. No refund of prepaid fees shall be provided upon termination for cause.

[PLACEHOLDER - ATTORNEY REVIEW REQUIRED]

10. DISPUTE RESOLUTION

Any dispute, controversy, or claim arising out of or relating to this Agreement, or the breach, termination, or validity thereof, shall first be subject to good-faith negotiation between the parties for a period of thirty (30) days following written notice of the dispute. If the dispute cannot be resolved through negotiation, it shall be submitted to binding arbitration administered by the American Arbitration Association under its Commercial Arbitration Rules. The arbitration shall be conducted by a single arbitrator in Austin, Texas. The arbitrator's decision shall be final and binding, and judgment upon the award may be entered in any court of competent jurisdiction. The parties agree that any arbitration shall be conducted on an individual basis and not as a class action, class arbitration, or representative action. The prevailing party in any arbitration or legal proceeding shall be entitled to recover its reasonable attorneys' fees and costs from the non-prevailing party. Notwithstanding the foregoing, either party may seek injunctive or other equitable relief in any court of competent jurisdiction to prevent the actual or threatened infringement of intellectual property rights.

[PLACEHOLDER - ATTORNEY REVIEW REQUIRED]

11. E-SIGN CONSENT

By creating an account on the Platform, clicking "I Agree," or otherwise electronically accepting these Terms of Service, the Subscriber consents to the use of electronic signatures, electronic records, and electronic delivery of notices and disclosures in connection with this Agreement and all transactions conducted through the Platform. The Subscriber acknowledges and agrees that electronic signatures and records shall have the same legal force and effect as manual signatures and paper records, in accordance with the Electronic Signatures in Global and National Commerce Act (E-SIGN Act, 15 U.S.C. 7001 et seq.) and applicable state laws, including the Uniform Electronic Transactions Act (UETA). The Subscriber represents that it has the technical capability to receive, access, and retain electronic records. The Subscriber may withdraw its consent to receive electronic records at any time by contacting customer support, provided that such withdrawal may result in the inability to continue using the Platform. A printed version of this Agreement and any notice delivered electronically shall be admissible in judicial or administrative proceedings.

[PLACEHOLDER - ATTORNEY REVIEW REQUIRED]

12. GOVERNING LAW

This Agreement shall be governed by and construed in accordance with the laws of the State of Texas, without regard to its conflict of laws principles. The parties agree that the United Nations Convention on Contracts for the International Sale of Goods shall not apply to this Agreement. Any legal action or proceeding not subject to arbitration as described in Section 10 shall be brought exclusively in the state or federal courts located in Travis County, Texas, and the parties hereby consent to the personal jurisdiction and venue of such courts. The Subscriber agrees that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to this Agreement or the use of the Platform must be filed within one (1) year after such claim or cause of action arose, or be forever barred. If any provision of this Agreement is found to be unenforceable or invalid by a court of competent jurisdiction, such provision shall be modified to the minimum extent necessary to make it enforceable, and the remaining provisions shall continue in full force and effect.

[PLACEHOLDER - ATTORNEY REVIEW REQUIRED]

13. CHANGES TO TERMS

Reyna Tech LLC reserves the right to modify, amend, or update these Terms of Service at any time at its sole discretion. When material changes are made, Reyna Tech LLC shall provide the Subscriber with notice through one or more of the following methods: (a) a prominent notice within the Platform's dashboard; (b) an email to the address associated with the Subscriber's account; or (c) a notification through the Platform's messaging system. Material changes shall become effective thirty (30) days after notice is provided, unless a longer period is required by applicable law. The Subscriber's continued use of the Platform after the effective date of any changes constitutes acceptance of the modified Terms. If the Subscriber does not agree to the modified Terms, the Subscriber must discontinue use of the Platform and cancel their subscription prior to the effective date of the changes. It is the Subscriber's responsibility to review these Terms periodically. The "Last Updated" date at the top of this document indicates the most recent revision.

[PLACEHOLDER - ATTORNEY REVIEW REQUIRED]

14. CONTACT INFORMATION

For questions, concerns, or notices regarding these Terms of Service, the Subscriber may contact Reyna Tech LLC through the following channels. For general inquiries and customer support: support@runmysalon.com. For legal notices and formal correspondence: legal@runmysalon.com. For data privacy inquiries and data subject access requests: privacy@runmysalon.com. Mailing address: Reyna Tech LLC, Attn: Legal Department, [ADDRESS PLACEHOLDER], Austin, TX [ZIP PLACEHOLDER]. All formal legal notices must be sent via certified mail, return receipt requested, or via email to legal@runmysalon.com with confirmation of receipt. Notices shall be deemed received upon the earlier of actual receipt or three (3) business days after mailing. The Subscriber is responsible for maintaining current and accurate contact information within their Platform account, as Reyna Tech LLC shall rely on such information for all communications, including billing notices, service announcements, and legal notices.

[PLACEHOLDER - ATTORNEY REVIEW REQUIRED]

END OF TERMS OF SERVICE - v0-placeholder

\u26a0\ufe0f REMINDER: This entire document is a placeholder. Every section requires review, revision, and approval by a licensed attorney before this document may be presented to users or relied upon for any legal purpose. Reyna Tech LLC assumes no liability for any use of this placeholder document as actual legal terms.
`

async function main() {
  await prisma.termsOfServiceVersion.upsert({
    where: { version: "v0-placeholder" },
    update: { content: PLACEHOLDER_TOS },
    create: {
      version: "v0-placeholder",
      content: PLACEHOLDER_TOS,
      effectiveDate: new Date(),
      isActive: false, // NOT active — must be replaced before launch
    },
  })
  console.log("Seeded placeholder ToS v0")
  await prisma.$disconnect()
}
main()
