/**
 * Models that have a tenantId column and must be queried through tenantDb().
 * If you add a new tenant-scoped model, add its Prisma MODEL name here (PascalCase).
 *
 * IMPORTANT: Prisma's $allModels extension passes model names in PascalCase
 * (e.g. "Client", not "client"). This set MUST use PascalCase to match.
 */
export const TENANT_SCOPED_MODELS: ReadonlySet<string> = new Set([
  "Location",
  "StaffMember",
  "InventoryItem",
  "Schedule",
  "Shift",
  "AdminAlert",
  "AlertRead",
  "PurchaseOrder",
  "PurchaseOrderItem",
  "ConductRecord",
  "OnboardingEnrollment",
  "Client",
  "ClientFormula",
  "CardOnFileRequest",
  "AppointmentNote",
  "FinancialAccount",
  "BankTransaction",
  "Expense",
  "Invoice",
  "BoothRental",
  "BoothRentalPayment",
  "TaxRecord",
  "ContractorPayment",
  "BusinessModel",
  "OffboardingRecord",
  "PayrollPeriod",
  "PayrollEntry",
  "AuditLog",
  "SocialPost",
  "SocialConnection",
  "WaitlistEntry",
  "PerformanceGoal",
  "PerformanceBonus",
  "RebookRecord",
  "ReviewRequest",
  "PortalPermission",
  "ChurnPrediction",
  "ReynaConversation",
  "ReynaKnowledge",
  "ApiKey",
  "GiftCard",
  "ReferralCode",
  "Referral",
  "LoyaltyAccount",
  "Membership",
  "MarketingCampaign",
  "KioskSession",
  "VoiceCallLog",
])
